spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_app?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: test1
  jpa:
    hibernate:
      ddl-auto: create-drop