spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_app?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop